package com.tms.configuaration.constant;

public enum ApprovalStatusType {
    STORE_DEMAND,
    STORE_ISSUE,
    PROCUREMENT_REQUISITION,
    STORE_RETURN,
    RETURN_UNSERVICEABLE,
    STORE_PART_LOAN,
    VENDOR,
    VENDOR_QUALITY,
    STORE_SCRAP,
    PROCUREMENT_RFQ,
    LOGISTIC_RFQ,
    STORE_INSPECTOR_CHECKLIST,
    STORE_INSPECTOR_CHECKLIST_QUALITY,
    STORE_WORK_ORDER,
    COMPARATIVE_STATEMENT,
    COMPARATIVE_STATEMENT_AUDIT,
    COMPARATIVE_STATEMENT_FINAL,
    PURCHASE_ORDER,
    LOGISTIC_PURCHASE_ORDER,
    PARTS_INVOICE,
    PARTS_INVOICE_AUDIT,
    PARTS_INVOICE_FINANCE
}
